-- AlterEnum
ALTER TYPE "ProjectSector" ADD VALUE 'EDUCATION';
ALTER TYPE "ProjectSector" ADD VALUE 'FOOD_FMCG';
ALTER TYPE "ProjectSector" ADD VALUE 'FORESTRY';
ALTER TYPE "ProjectSector" ADD VALUE 'CONSTRUCTION';
ALTER TYPE "ProjectSector" ADD VALUE 'INFRASTRUCTURE';
ALTER TYPE "ProjectSector" ADD VALUE 'LOGISTICS';
ALTER TYPE "ProjectSector" ADD VALUE 'MANUFACTURING';
ALTER TYPE "ProjectSector" ADD VALUE 'MINING_MINERALS';
ALTER TYPE "ProjectSector" ADD VALUE 'ICT';
ALTER TYPE "ProjectSector" ADD VALUE 'FINTECH';
ALTER TYPE "ProjectSector" ADD VALUE 'TELECOM';
ALTER TYPE "ProjectSector" ADD VALUE 'RETAIL';
ALTER TYPE "ProjectSector" ADD VALUE 'MEDIA_CREATIVE';
ALTER TYPE "ProjectSector" ADD VALUE 'WATER_SANITATION';
ALTER TYPE "ProjectSector" ADD VALUE 'WASTE_CIRCULAR';
ALTER TYPE "ProjectSector" ADD VALUE 'SOCIAL_IMPACT';
ALTER TYPE "ProjectSector" ADD VALUE 'OTHER';
